### ISSUE TITLE
gzip set up for nodejs/express

### ISSUE THREAD

**Issue by jodychen** [jodychen/biglotus#32]
### Information about gzip
- http://betterexplained.com/articles/how-to-optimize-your-site-with-gzip-compression/
- http://betterexplained.com/articles/speed-up-your-javascript-load-time/
- https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/optimize-encoding-and-transfer
### Tool to confirm gzip

http://www.gidnetwork.com/tools/gzip-test.php

See also wiki article on web performance

**Comment by yzandy** [comment]
done, and Jody verified
